# Generated by Django 5.0 on 2024-02-11 11:14

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerSports', '0002_city_field_city_field_date_time_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_players', models.IntegerField()),
                ('date', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('time', models.CharField(default='', max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PowerSports.address')),
            ],
        ),
    ]
