# Generated by Django 5.0 on 2024-02-11 11:49

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerSports', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
