# Generated by Django 5.0 on 2024-02-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerSports', '0004_booking_city_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PowerSports.city'),
        ),
    ]
