# Generated by Django 5.0 on 2024-02-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerSports', '0005_alter_booking_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
