# Generated by Django 5.0 on 2024-02-14 17:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PowerSports', '0006_alter_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='players_needed',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='sport',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
