# Generated by Django 5.0 on 2024-02-14 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PowerSports', '0009_remove_booking_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='players_needed',
        ),
    ]
